// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pregiato.API.Data;

#nullable disable

namespace Pregiato.API.Migrations
{
    [DbContext(typeof(ModelAgencyContext))]
    [Migration("20250329073203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pregiato.API.Models.ContractBase", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodProducers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CodProposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(400);

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContractFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataContrato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdModel")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModelIdModel")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusContratc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorContrato")
                        .HasColumnType("numeric");

                    b.Property<string>("VigenciaContrato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContractId");

                    b.HasIndex("CodProducers");

                    b.HasIndex("ModelIdModel");

                    b.ToTable("Contracts", (string)null);

                    b.HasDiscriminator<string>("ContractType").HasValue("ContractBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Pregiato.API.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IdModel")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobId");

                    b.HasIndex("IdModel");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Pregiato.API.Models.Model", b =>
                {
                    b.Property<Guid>("IdModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ModelId")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodProducers")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<JsonDocument>("DNA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("TelefonePrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefoneSecundario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("IdModel");

                    b.HasIndex("CPF");

                    b.HasIndex("CodProducers");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("Pregiato.API.Models.ModelJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdditionalDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Time")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelJob", (string)null);
                });

            modelBuilder.Entity("Pregiato.API.Models.ModelsBilling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdModel")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdModel");

                    b.HasIndex("JobId");

                    b.ToTable("ModelsBilling", (string)null);
                });

            modelBuilder.Entity("Pregiato.API.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutorizationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodProducers")
                        .HasColumnType("text");

                    b.Property<byte[]>("Comprovante")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAcordoPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalCartao")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeParcela")
                        .HasColumnType("integer");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("PaymentId");

                    b.HasIndex("CodProducers");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Pregiato.API.Models.Producers", b =>
                {
                    b.Property<string>("CodProducers")
                        .HasColumnType("text");

                    b.Property<decimal>("AmountContract")
                        .HasColumnType("numeric");

                    b.Property<int>("CodProposal")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InfoModel")
                        .HasColumnType("jsonb");

                    b.Property<string>("NameProducer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusContratc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAgreements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ValidityContract")
                        .HasColumnType("text");

                    b.HasKey("CodProducers");

                    b.HasIndex("ContractId");

                    b.ToTable("Producers", (string)null);
                });

            modelBuilder.Entity("Pregiato.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CodProducers")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("CodProducers");

                    b.HasIndex("Name");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Pregiato.API.Models.AgencyContract", b =>
                {
                    b.HasBaseType("Pregiato.API.Models.ContractBase");

                    b.HasDiscriminator().HasValue("Agency");
                });

            modelBuilder.Entity("Pregiato.API.Models.CommitmentTerm", b =>
                {
                    b.HasBaseType("Pregiato.API.Models.ContractBase");

                    b.HasDiscriminator().HasValue("Commitment");
                });

            modelBuilder.Entity("Pregiato.API.Models.ImageRightsTerm", b =>
                {
                    b.HasBaseType("Pregiato.API.Models.ContractBase");

                    b.HasDiscriminator().HasValue("ImageRights");
                });

            modelBuilder.Entity("Pregiato.API.Models.PhotographyProductionContract", b =>
                {
                    b.HasBaseType("Pregiato.API.Models.ContractBase");

                    b.HasDiscriminator().HasValue("PhotographyProduction");
                });

            modelBuilder.Entity("Pregiato.API.Models.PhotographyProductionContractMinority", b =>
                {
                    b.HasBaseType("Pregiato.API.Models.ContractBase");

                    b.HasDiscriminator().HasValue("PhotographyMinority");
                });

            modelBuilder.Entity("Pregiato.API.Models.ContractBase", b =>
                {
                    b.HasOne("Pregiato.API.Models.Producers", "Producers")
                        .WithMany()
                        .HasForeignKey("CodProducers")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pregiato.API.Models.Model", null)
                        .WithMany("Contracts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pregiato.API.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelIdModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Producers");
                });

            modelBuilder.Entity("Pregiato.API.Models.Job", b =>
                {
                    b.HasOne("Pregiato.API.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("IdModel")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Pregiato.API.Models.Model", b =>
                {
                    b.HasOne("Pregiato.API.Models.Producers", "Producers")
                        .WithMany()
                        .HasForeignKey("CodProducers");

                    b.Navigation("Producers");
                });

            modelBuilder.Entity("Pregiato.API.Models.ModelJob", b =>
                {
                    b.HasOne("Pregiato.API.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("Pregiato.API.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.Navigation("Job");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Pregiato.API.Models.ModelsBilling", b =>
                {
                    b.HasOne("Pregiato.API.Models.Model", "Model")
                        .WithMany("Billings")
                        .HasForeignKey("IdModel")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pregiato.API.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.Navigation("Job");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Pregiato.API.Models.Payment", b =>
                {
                    b.HasOne("Pregiato.API.Models.Producers", "Producers")
                        .WithMany()
                        .HasForeignKey("CodProducers")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pregiato.API.Models.ContractBase", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contract");

                    b.Navigation("Producers");
                });

            modelBuilder.Entity("Pregiato.API.Models.Producers", b =>
                {
                    b.HasOne("Pregiato.API.Models.ContractBase", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Pregiato.API.Models.Model", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
